### ISSUE TITLE
xF_jd_health_plant.py 报错？

### ISSUE THREAD

**Issue by jjjyyyllll** [zyf1118/kevinxf#10]
日志 

[2022-02-16 13:46:58]: 【账号******】加购任务已全部完成
{'message': '今日充值次数达到上限', 'status_code': 422, 'debug': {'line': 210, 'file': '/home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Response/Factory.php', 'class': 'Symfony\\Component\\HttpKernel\\Exception\\HttpException', 'trace': ['#0 /home/deploy/healthy-plant2021/releases/52/app/Http/Controllers/Api/ActiveController.php(352): Dingo\\Api\\Http\\Response\\Factory->error()', '#1 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\ActiveController->AddGrowthValue()', '#2 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()', '#3 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()', '#4 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()', '#5 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()', '#6 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()', '#7 /home/deploy/healthy-plant2021/releases/52/app/Http/Middleware/CheckWhite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#8 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckWhite->handle()', '#9 /home/deploy/healthy-plant2021/releases/52/app/Http/Middleware/CheckRiskUser.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#10 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckRiskUser->handle()', '#11 /home/deploy/healthy-plant2021/releases/52/app/Http/Middleware/CheckActivity.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#12 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckActivity->handle()', '#13 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Auth.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#14 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Auth->handle()', '#15 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#16 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()', '#17 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#18 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\PrepareController->handle()', '#19 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#20 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()', '#21 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()', '#22 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()', '#23 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()', '#24 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): Illuminate\\Routing\\Router->dispatch()', '#25 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Routing/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch()', '#26 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch()', '#27 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}()', '#28 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#29 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()', '#30 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#31 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()', '#32 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#33 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()', '#34 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#35 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()', '#36 /home/deploy/healthy-plant2021/releases/52/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#37 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()', '#38 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#39 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then()', '#40 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter()', '#41 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Request->handle()', '#42 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#43 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()', '#44 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()', '#45 /home/deploy/healthy-plant2021/releases/52/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()', '#46 {main}']}}

[2022-02-16 13:47:41]: 【*******】加购任务已全部完成
{'message': '该植物不能充值', 'status_code': 422, 'debug': {'line': 210, 'file': '/home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Response/Factory.php', 'class': 'Symfony\\Component\\HttpKernel\\Exception\\HttpException', 'trace': ['#0 /home/deploy/healthy-plant2021/releases/52/app/Http/Controllers/Api/ActiveController.php(352): Dingo\\Api\\Http\\Response\\Factory->error()', '#1 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\ActiveController->AddGrowthValue()', '#2 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()', '#3 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()', '#4 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()', '#5 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()', '#6 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()', '#7 /home/deploy/healthy-plant2021/releases/52/app/Http/Middleware/CheckWhite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#8 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckWhite->handle()', '#9 /home/deploy/healthy-plant2021/releases/52/app/Http/Middleware/CheckRiskUser.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#10 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckRiskUser->handle()', '#11 /home/deploy/healthy-plant2021/releases/52/app/Http/Middleware/CheckActivity.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#12 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckActivity->handle()', '#13 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Auth.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#14 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Auth->handle()', '#15 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#16 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()', '#17 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#18 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\PrepareController->handle()', '#19 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#20 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()', '#21 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()', '#22 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()', '#23 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()', '#24 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): Illuminate\\Routing\\Router->dispatch()', '#25 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Routing/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch()', '#26 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch()', '#27 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}()', '#28 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#29 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()', '#30 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#31 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()', '#32 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#33 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()', '#34 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#35 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()', '#36 /home/deploy/healthy-plant2021/releases/52/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#37 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()', '#38 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#39 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then()', '#40 /home/deploy/healthy-plant2021/releases/52/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter()', '#41 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Request->handle()', '#42 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()', '#43 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()', '#44 /home/deploy/healthy-plant2021/releases/52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()', '#45 /home/deploy/healthy-plant2021/releases/52/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()', '#46 {main}']}}

**Comment by zyf1118** [comment]
JD的两个种植园活动都火爆了
